branch-defaults:
  main:
    environment: MyEnvironmentName
    group_suffix: null
global:
  application_name: myapp
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
