name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV # <-- Specify the environment here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t olagunju/jennifer:latest .
          docker push olagunju/jennifer:latest

    
      - name: Deploy to Elastic Beanstalk
        run: |
            pip install awsebcli
            mkdir -p ~/.aws  # <-- Ensure the directory exists
            echo "[default]" >> ~/.aws/credentials  # <-- Add a default profile
            echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY }}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials
            echo "[default]" >> ~/.aws/config  # <-- Add a default profile
            echo "region = us-east-1" >> ~/.aws/config
            eb deploy
        
