name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t DOCKER_HUB_USERNAME/REPOSITORY_NAME:latest .
          docker push DOCKER_HUB_USERNAME/REPOSITORY_NAME:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          pip install awsebcli
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY }}" >> 
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY }}" >> ~/.aws/credentials
          echo "region = us-east-1" >> ~/.aws/config
          eb deploy
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
